modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="reskillable"
version="3.0.3"
displayName="Reskillable Reborn"
logoFile="reskillable.png"
credits=""
authors="INPVLSA, majik, lanse505, pupnewfster, Jaredlll08, Sky_Som, Buuz135, Vazkii, CFGrafanaStats"
description='''
Reskillable is a mod about leveling various skills up, using XP.
Leveling skills up allow you to unlock traits and use more items.
By default, a lot of vanilla items are locked to require leveling your skills up
'''
[[dependencies.reskillable]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reskillable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
